# Generated by Django 5.2.11 on 2026-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('graduation_year', models.IntegerField()),
                ('role_company', models.CharField(max_length=300)),
                ('quote', models.TextField()),
            ],
        ),
    ]
