# Generated by Django 5.2.11 on 2026-09-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
