# Generated by Django 5.2.11 on 2026-08-21 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgFundingDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Optional cap on how many requests may select this date.', null=True)),
                ('is_open', models.BooleanField(default=True, help_text='When off, the date is hidden from the public form but kept for records.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('date', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrgFundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_email', models.EmailField(max_length=255)),
                ('m_number', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('involves_travel', models.BooleanField(default=False)),
                ('additional_contacts', models.JSONField(blank=True, default=list)),
                ('w9', models.FileField(blank=True, null=True, upload_to='org_funding/w9/')),
                ('application', models.FileField(blank=True, null=True, upload_to='org_funding/applications/')),
                ('slides', models.FileField(blank=True, null=True, upload_to='org_funding/slides/')),
                ('travel_authorization', models.FileField(blank=True, null=True, upload_to='org_funding/travel_auth/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In review'), ('approved', 'Approved'), ('denied', 'Denied'), ('funded', 'Funded')], default='pending', max_length=20)),
                ('checklist_w9', models.BooleanField(default=False)),
                ('checklist_application', models.BooleanField(default=False)),
                ('checklist_slides', models.BooleanField(default=False)),
                ('checklist_travel_authorization', models.BooleanField(default=False)),
                ('chair_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='org_funding.orgfundingdate')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
