# Generated by Django 5.2.11 on 2026-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('m_number', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('vendor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('budgeted', models.BooleanField(default=False)),
                ('reimbursement_type', models.CharField(max_length=255)),
                ('itemized_receipt', models.FileField(blank=True, null=True, upload_to='itemized_receipts/')),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='m_number',
            field=models.CharField(default='M16380810', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
