# Generated by Django 5.2.11 on 2026-04-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursement", "0003_reimbursement_optional_expenditure_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="m_number",
        ),
    ]
