# Generated by Django 5.2.11 on 2026-04-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursement", "0004_remove_userprofile_m_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reimbursementrequest",
            name="approving_officer_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="reimbursementrequest",
            name="approving_officer_position",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
