# Generated by Django 5.2.11 on 2026-07-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reimbursement', '0005_reimbursementrequest_approving_officer_name_and_more'),
        ('reimbursement', '0006_reimbursementrequest_extra_fields'),
    ]

    operations = [
    ]
