# Generated by Django 5.2.11 on 2026-08-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reimbursement", "0007_merge_20260725_2154"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reimbursementrequest",
            name="approving_officer_name",
        ),
        migrations.RemoveField(
            model_name="reimbursementrequest",
            name="approving_officer_position",
        ),
    ]
