# Generated by Django 4.2.7 on 2025-08-26 22:44

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecMember',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('imgURL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ExecMember', models.ManyToManyField(to='dashboard.execmember')),
            ],
        ),
    ]
