# Generated by Django 5.1.8 on 2025-04-02 22:22

import cuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecMember',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('imgURL', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ExecMember', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.execmember')),
            ],
        ),
    ]
