# Generated by Django 5.1.8 on 2025-04-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execmember',
            name='imgURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
