# Generated by Django 4.2.7 on 2025-09-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="execrole",
            name="committee",
            field=models.CharField(
                choices=[
                    ("pres", "President"),
                    ("cos", "Chief of Staff"),
                    ("vpe", "Events Committees"),
                    ("vpca", "Collegiate Affairs Committees"),
                ],
                default=("pres", "President"),
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
