# Generated by Django 5.2.11 on 2026-03-05 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_execrole_committee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='execmember',
            name='name',
        ),
        migrations.AddField(
            model_name='execmember',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
