# Generated by Django 5.1.8 on 2025-04-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_execmember_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='execrole',
            name='ExecMember',
        ),
        migrations.AddField(
            model_name='execrole',
            name='ExecMember',
            field=models.ManyToManyField(to='dashboard.execmember'),
        ),
    ]
