# Generated by Django 5.2.11 on 2026-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_execmember_email_remove_execmember_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execmember',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
