# Generated by Django 5.2.11 on 2026-04-04 22:29

import cuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('booth_location', models.CharField(max_length=250)),
                ('building_location', models.CharField(max_length=250)),
                ('signed_in_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-signed_in_at'],
            },
        ),
    ]
