# Generated by Django 5.2.11 on 2026-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_fair", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="representative",
            name="is_printed",
            field=models.BooleanField(default=False),
        ),
    ]
