# Generated by Django 4.2.7 on 2025-11-11 22:28

import cuid
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecMember',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('imgURL', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeReviewEmployer',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('diet_restriction', models.CharField(null=True)),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('max_resumes', models.IntegerField(max_length=2)),
                ('uc_almuni', models.BooleanField()),
                ('selected_majors', multiselectfield.db.fields.MultiSelectField(choices=[('aero', 'Aerospace Engineering'), ('arch', 'Architechtual Engineering'), ('bmes', 'Biomedical Engineering'), ('chem', 'Chemical Engineering'), ('civil', 'Civil Engineering'), ('cs', 'Computer Science'), ('compe', 'Computer Engineering'), ('const', 'Construction Management'), ('cyber', 'Cybersecurity Engineering'), ('elec', 'Electrical Engineering'), ('elect', 'Electrical Engineering Technology'), ('ise', 'Industrial & Systems Engineering'), ('mech', 'Mechanical Engineering'), ('mecht', 'Mechanical Engineering Technology')], max_length=72)),
            ],
        ),
    ]
