# Generated by Django 4.2.7 on 2025-11-11 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0002_alter_resumereviewemployer_max_resumes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExecMember',
        ),
    ]
