# Generated by Django 4.2.7 on 2025-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0003_delete_execmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumereviewemployer',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='resumereviewemployer',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
