# Generated by Django 4.2.7 on 2025-11-12 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0004_alter_resumereviewemployer_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumereviewemployer',
            name='max_resumes',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
