# Generated by Django 4.2.7 on 2025-11-12 21:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0005_alter_resumereviewemployer_max_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumereviewemployer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
