# Generated by Django 4.2.7 on 2025-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0006_alter_resumereviewemployer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumereviewemployer',
            name='diet_restriction',
            field=models.CharField(blank=True, null=True),
        ),
    ]
