# Generated by Django 4.2.7 on 2025-11-12 23:01

import cuid
import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0007_alter_resumereviewemployer_diet_restriction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('diet_restriction', models.CharField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_resumes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('uc_almuni', models.BooleanField()),
                ('selected_majors', multiselectfield.db.fields.MultiSelectField(choices=[('aero', 'Aerospace Engineering'), ('arch', 'Architechtual Engineering'), ('bmes', 'Biomedical Engineering'), ('chem', 'Chemical Engineering'), ('civil', 'Civil Engineering'), ('cs', 'Computer Science'), ('compe', 'Computer Engineering'), ('const', 'Construction Management'), ('cyber', 'Cybersecurity Engineering'), ('elec', 'Electrical Engineering'), ('elect', 'Electrical Engineering Technology'), ('ise', 'Industrial & Systems Engineering'), ('mech', 'Mechanical Engineering'), ('mecht', 'Mechanical Engineering Technology')], max_length=72)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('grad_year', models.IntegerField()),
                ('major', models.CharField(choices=[('aero', 'Aerospace Engineering'), ('arch', 'Architechtual Engineering'), ('bmes', 'Biomedical Engineering'), ('chem', 'Chemical Engineering'), ('civil', 'Civil Engineering'), ('cs', 'Computer Science'), ('compe', 'Computer Engineering'), ('const', 'Construction Management'), ('cyber', 'Cybersecurity Engineering'), ('elec', 'Electrical Engineering'), ('elect', 'Electrical Engineering Technology'), ('ise', 'Industrial & Systems Engineering'), ('mech', 'Mechanical Engineering'), ('mecht', 'Mechanical Engineering Technology')], max_length=30)),
                ('resume', models.FileField(upload_to='resumes/')),
            ],
        ),
        migrations.DeleteModel(
            name='ResumeReviewEmployer',
        ),
    ]
