# Generated by Django 4.2.7 on 2025-11-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0008_employers_students_delete_resumereviewemployer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employers',
            new_name='Employer',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
