# Generated by Django 4.2.7 on 2025-11-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0009_rename_employers_employer_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='uc_almuni',
            new_name='uc_alumni',
        ),
    ]
