# Generated by Django 4.2.7 on 2025-11-13 01:39

import cuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0010_rename_uc_almuni_employer_uc_alumni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.CharField(default=cuid.cuid, max_length=25, primary_key=True, serialize=False)),
                ('timeslot', models.TimeField()),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResumeReviewDay.employer')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ResumeReviewDay.student')),
            ],
        ),
    ]
