# Generated by Django 4.2.7 on 2026-01-20 23:28

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("ResumeReviewDay", "0011_timeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employer",
            name="selected_majors",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("aero", "Aerospace Engineering"),
                    ("arch", "Architechtual Engineering"),
                    ("bmes", "Biomedical Engineering"),
                    ("chem", "Chemical Engineering"),
                    ("civil", "Civil Engineering"),
                    ("cs", "Computer Science"),
                    ("compe", "Computer Engineering"),
                    ("const", "Construction Management"),
                    ("cyber", "Cybersecurity Engineering"),
                    ("elec", "Electrical Engineering"),
                    ("elect", "Electrical Engineering Technology"),
                    ("ise", "Industrial & Systems Engineering"),
                    ("mech", "Mechanical Engineering"),
                    ("mecht", "Mechanical Engineering Technology"),
                ],
                max_length=200,
            ),
        ),
    ]
