# Generated by Django 5.2.11 on 2026-08-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeReviewDay', '0012_alter_employer_selected_majors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeReviewSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('employer_page_open', models.BooleanField(default=True)),
                ('student_page_open', models.BooleanField(default=True)),
            ],
        ),
    ]
